<?php

use App\Models\code_table;
use Illuminate\Database\Seeder;

class CodetablesTableSeeder extends Seeder
{
    public function run()
    {
        $code_tables = [[
                'id'            => '1',
                'sys_code_type' => '1',
                'sys_code'      => '1',
                'name'          => 'red',
                'name_ar'       => 'أحمر',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '2',
                'sys_code_type' => '1',
                'sys_code'      => '2',
                'name'          => 'Black',
                'name_ar'       => 'أسود',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '3',
                'sys_code_type' => '1',
                'sys_code'      => '3',
                'name'          => 'Blue',
                'name_ar'       => 'أزرق',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '4',
                'sys_code_type' => '1',
                'sys_code'      => '4',
                'name'          => 'Brown',
                'name_ar'       => 'بنى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '5',
                'sys_code_type' => '1',
                'sys_code'      => '5',
                'name'          => 'Orange',
                'name_ar'       => 'برتقالى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '6',
                'sys_code_type' => '1',
                'sys_code'      => '6',
                'name'          => 'Yellow',
                'name_ar'       => 'أصفر',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '7',
                'sys_code_type' => '1',
                'sys_code'      => '7',
                'name'          => 'White',
                'name_ar'       => 'أبيض',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '8',
                'sys_code_type' => '1',
                'sys_code'      => '8',
                'name'          => 'Pink',
                'name_ar'       => 'بمبى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '9',
                'sys_code_type' => '1',
                'sys_code'      => '9',
                'name'          => 'Green',
                'name_ar'       => 'أخضر',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '10',
                'sys_code_type' => '1',
                'sys_code'      => '10',
                'name'          => 'Grey',
                'name_ar'       => 'رصاصى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '11',
                'sys_code_type' => '1',
                'sys_code'      => '11',
                'name'          => 'Blue-Violet',
                'name_ar'       => 'بنفسجى مزرق',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '12',
                'sys_code_type' => '1',
                'sys_code'      => '12',
                'name'          => 'Silver',
                'name_ar'       => 'فضى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '13',
                'sys_code_type' => '1',
                'sys_code'      => '13',
                'name'          => 'Tan',
                'name_ar'       => 'سمنى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '14',
                'sys_code_type' => '1',
                'sys_code'      => '14',
                'name'          => 'Beige',
                'name_ar'       => 'بيج',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '15',
                'sys_code_type' => '1',
                'sys_code'      => '15',
                'name'          => 'Lime',
                'name_ar'       => 'ليمونى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '16',
                'sys_code_type' => '1',
                'sys_code'      => '16',
                'name'          => 'Lawn green',
                'name_ar'       => 'أخضر مصفر',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '17',
                'sys_code_type' => '1',
                'sys_code'      => '17',
                'name'          => 'Olive',
                'name_ar'       => 'زيتونى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '18',
                'sys_code_type' => '1',
                'sys_code'      => '18',
                'name'          => 'Gold',
                'name_ar'       => 'ذهبى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '19',
                'sys_code_type' => '1',
                'sys_code'      => '19',
                'name'          => 'Orange-Red',
                'name_ar'       => 'أحمر برتقالى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '20',
                'sys_code_type' => '1',
                'sys_code'      => '20',
                'name'          => 'Violet',
                'name_ar'       => 'موف',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '21',
                'sys_code_type' => '1',
                'sys_code'      => '21',
                'name'          => 'Purple',
                'name_ar'       => 'أرجوانى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '22',
                'sys_code_type' => '1',
                'sys_code'      => '22',
                'name'          => 'Navy',
                'name_ar'       => 'كحلى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '23',
                'sys_code_type' => '1',
                'sys_code'      => '23',
                'name'          => 'Salmon',
                'name_ar'       => 'كشميرى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '24',
                'sys_code_type' => '1',
                'sys_code'      => '24',
                'name'          => 'Cyan',
                'name_ar'       => 'أزرق سماوى',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '25',
                'sys_code_type' => '2',
                'sys_code'      => '1',
                'name'          => 'BMW',
                'name_ar'       => 'بى ام دبليو',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '26',
                'sys_code_type' => '2',
                'sys_code'      => '2',
                'name'          => 'Fiat',
                'name_ar'       => 'فيات',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '27',
                'sys_code_type' => '3',
                'sys_code'      => '1',
                'name'          => 'Crashed',
                'name_ar'       => 'مصدومة',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '28',
                'sys_code_type' => '3',
                'sys_code'      => '2',
                'name'          => 'Scratched',
                'name_ar'       => 'مخدوشة',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '29',
                'sys_code_type' => '4',
                'sys_code'      => '1',
                'name'          => '300*300',
                'name_ar'       => '300*300',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '30',
                'sys_code_type' => '4',
                'sys_code'      => '2',
                'name'          => '300*200',
                'name_ar'       => '300*200',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],
            [
                'id'            => '31',
                'sys_code_type' => '5',
                'sys_code'      => '1',
                'name'          => 'Fast',
                'name_ar'       => 'سريغ',
                'created_at' => '2020-04-15 19:14:42',
                'updated_at' => '2020-04-15 19:14:42',
            ],

        ];

        code_table::insert($code_tables);
    }
}
